apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2R0aS1yZWdpc3Ryby51bmlsYWIuZWR1LmJyIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IkR0aUB1bmlsYWIyMDIzIiwiZW1haWwiOiJkaXNpckB1bmlsYWIuZWR1LmJyIiwiYXV0aCI6IllXUnRhVzQ2UkhScFFIVnVhV3hoWWpJd01qTT0ifX19
kind: Secret
metadata:
  name: harbor-registro 
  namespace: docker
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: erivando/maven:3.9.0-openjdk-11 #maven:3.8.6-openjdk-11
      #command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      #command: ["/bin/sh -cp"]
      #args: ["sleep", "9999999"]
      tty: true
      imagePullPolicy: Always # use cache or pull image for agent
      resources:  # limits the resources your build contaienr
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "5000m"
          memory: "3Gi"
      env:
      - name: JENKINS_URL
        value: "http://jenkins.jenkins.svc.cluster.local"
      - name: JENKINS_TUNNEL
        value: "jenkins.jenkins.svc.cluster.local:"
    - name: docker
      image: docker:20.10 #dti-registro.unilab.edu.br/unilab/docker:latest
      #command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: IfNotPresent
      resources: {}
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
  imagePullSecrets:
  - name: harbor-registro
