apiVersion: v1
kind: Pod
metadata:
  name: slave
  namespace: jenkins
  labels:
    jenkins: slave
spec:
  containers:  # lista de contêineres que você deseja apresentar para sua compilação, pode definir um contêiner padrão no Jenkinsfile
    - name: maven
      image: erivando/maven:3.9.0-openjdk-11 # imagem customizada
      #command: ["tail", "-f", "/dev/null"]  # este ou qualquer comando que seja basicamente um noop é necessário, isso é para que não substitua o ponto de entrada do contêiner base
      imagePullPolicy: Always # use o cache ou puxe a imagem para o agente
      resources:  # limites e recursos que o build contém
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "5000m"
          memory: "3Gi"
    - name: docker
      image: docker:20.10 #dti-registro.unilab.edu.br/unilab/docker:latest
      #command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: IfNotPresent
      resources: {}
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # Usao do mecanismo do docker do host k8s
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
  #imagePullSecrets:
  #- name: harbor-registro
